**Load Data**

In [1]:
import pandas as pd

df = pd.read_csv("Loan_Default_Raw.csv")

In [2]:
df.head()

,ID,year,loan_limit,Gender,approv_in_adv,loan_type,loan_purpose,Credit_Worthiness,open_credit,business_or_commercial,...,credit_type,Credit_Score,co-applicant_credit_type,age,submission_of_application,LTV,Region,Security_Type,Status,dtir1
0,49802,2019,cf,Female,nopre,type2,p3,l1,nopc,b/c,...,EXP,679,CIB,45-54,to_inst,84.420290,North,direct,0,41.0
1,171958,2019,cf,Sex Not Available,pre,type1,p4,l1,nopc,nob/c,...,EXP,853,EXP,25-34,to_inst,88.246269,south,direct,0,44.0
2,148174,2019,cf,Sex Not Available,nopre,type1,p3,l1,nopc,nob/c,...,CRIF,598,EXP,65-74,to_inst,19.279661,south,direct,0,41.0
3,78500,2019,cf,Female,nopre,type1,p3,l1,nopc,nob/c,...,EXP,776,EXP,65-74,to_inst,36.228814,North,direct,0,32.0
4,64562,2019,cf,Female,nopre,type1,p1,l1,nopc,nob/c,...,EXP,653,CIB,35-44,not_inst,81.921241,North,direct,0,48.0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 34 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ID                         15000 non-null  int64
 1   year                       15000 non-null  int64
 2   loan_limit                 14679 non-null  object
 3   Gender                     15000 non-null  object
 4   approv_in_adv              14900 non-null  object
 5   loan_type                  15000 non-null  object
 6   loan_purpose               14993 non-null  object
 7   Credit_Worthiness          15000 non-null  object
 8   open_credit                15000 non-null  object
 9   business_or_commercial     15000 non-null  object
 10  loan_amount                15000 non-null  int64
 11  rate_of_interest           11468 non-null  float64
 12  Interest_rate_spread       11442 non-null  float64
 13  Upfront_charges            11130 non-null  float64
 14  term                       14995 non-null  float64
 15  Neg_ammortization          14992 non-null  object
 16  interest_only              15000 non-null  object
 17  lump_sum_payment           15000 non-null  object
 18  property_value             13537 non-null  float64
 19  construction_type          15000 non-null  object
 20  occupancy_type             15000 non-null  object
 21  Secured_by                 15000 non-null  object
 22  total_units                15000 non-null  object
 23  income                     14070 non-null  float64
 24  credit_type                15000 non-null  object
 25  Credit_Score               15000 non-null  int64
 26  co-applicant_credit_type   15000 non-null  object
 27  age                        14974 non-null  object
 28  submission_of_application  14974 non-null  object
 29  LTV                        13537 non-null  float64
 30  Region                     15000 non-null  object
 31  Security_Type              15000 non-null  object
 32  Status                     15000 non-null  int64
 33  dtir1                      12614 non-null  float64
dtypes: float64(8), int64(5), object(21)
memory usage: 3.9+ MB

In [4]:
df.shape

(15000, 34)

**Check Missing Values**

In [5]:
df.isnull().sum()

ID                              0
year                            0
loan_limit                    321
Gender                          0
approv_in_adv                 100
loan_type                       0
loan_purpose                    7
Credit_Worthiness               0
open_credit                     0
business_or_commercial          0
loan_amount                     0
rate_of_interest             3532
Interest_rate_spread         3558
Upfront_charges              3870
term                            5
Neg_ammortization               8
interest_only                   0
lump_sum_payment                0
property_value               1463
construction_type               0
occupancy_type                  0
Secured_by                      0
total_units                     0
income                        930
credit_type                     0
Credit_Score                    0
co-applicant_credit_type        0
age                            26
submission_of_application      26
LTV                          1463
Region                          0
Security_Type                   0
Status                          0
dtir1                        2386
dtype: int64

**Handle Missing Values**

In [6]:
for col in df.select_dtypes(include='number'):
    df[col].fillna(df[col].median(), inplace=True)


for col in df.select_dtypes(include='object'):
    df[col].fillna(df[col].mode()[0], inplace=True)

/tmp/ipykernel_1512/116032910.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
/tmp/ipykernel_1512/116032910.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

**Remove Duplicates**

In [7]:
df.drop_duplicates(inplace=True)

**Clean Column Names**

In [8]:
df.columns = df.columns.str.lower().str.strip()

**Clean Text Data**

In [9]:
for col in df.select_dtypes(include='object'):
    df[col] = df[col].str.lower().str.strip()

**Save Cleaned Data**

In [10]:
df.to_csv("loan_stage1_cleaned.csv", index=False)